name: CI

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Black (check)
        run: black --check src tests

      - name: isort (check)
        run: isort --check-only src tests

      - name: Flake8
        run: flake8 src tests

      - name: mypy
        run: mypy .

      - name: Run tests
        run: pytest -q
